# Generated by Django 3.2.8 on 2021-11-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, default=0, verbose_name='Date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=0, verbose_name='Date published'),
            preserve_default=False,
        ),
    ]
