# Generated by Django 3.2.8 on 2021-11-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211110_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='question',
            name='date_published',
        ),
    ]
